source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-relative-links"
  gem "jekyll-seo-tag"
  gem "jekyll-include-cache"
  gem "jekyll-remote-theme"
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", install_if: Gem.win_platform?
gem "public_suffix", "~> 4.0.6"
gem "webrick"
gem "csv"
gem "bigdecimal"
gem "ostruct"
